* Introduction


  - 3 phases
  - Apprenticeship
    - Learning as much as we can of the basic elements and rules
  - Creative Active
    - through practice and immersion, we see into the inside of machinery
    - how things connect with each other
    - ability to experiment and creatively play with the elements
  - Mastery
    - now we see the whole picture with clarity
    - we have access to the heart of life - to human nature and
      natural phenomena


  - Masters return to the childlike state, their works displaying
    degrees of spontaneity and access to the unconscious, but at a
    much higher level than the child.
  - Power of time
    - long stretch of time plays a critical, elemental role in our
      mental development.
    - For animals, time is great enemy. But our hunting ancestors
      reversed this process.
    - The longer they spent observing something, the deeper their
      understanding and connection with reality becomes.
    - The body could decay but their mind would continue to learn and
      adapt.
    - Using time for such effect is the essential ingredient of
      mastery.
    - With the element of time working for us, we can reverse the bad
      habits and passivity and move up the ladder of intelligence.
    - Think of this shift as a return to your radical, deep past as a
      hunter connecting to and maintaining a magnificent continuity
      with your hunter-gatherer ancestors in a modern form. The
      environment we operate in may be different, but the brain is
      essentially the same and its power to learn, adapt and master
      time is universal.


  - At the core is in fact a quality that is genetic and inborn - not
    tallent or brilliance which is something that must be developed
    but rather a deep and powerful inclination towards a subject.
  - Masters experience it as an inner calling. It tends to dominate
    their thoughts and dreams.
  - This intense connection and desire allows them to withstand the
    pain of the process - self doubts, tedious hours of practice and
    study, inevitable setbacks, endless barbs from the envious. They
    develop a resiliency and confidence that others lack.
  - In our culture, we tend to equate thinking and intellectual powers
    with success and achievement. In many ways, however, it is an
    emotional quality that separates those who master a field from the
    many who simply work it as a job.
  - Our levels of desire, patience, persistence and confidence end up
    playing a much larger role in success than sheer reasoning
    powers. Feeling motivated and energized, we can overcome almost anything.


  - If we dont try too much in life, if we limit our circle of action,
    we can give ourselves the illusion of control. The less we
    attempt, the less chances of failure.
  - We become attracted to certain narratives : it is genetics that
    determines much of what we do; we are just products our times; the
    individual is just a myth; human behaviour can be reduced to
    statistical trends.


  - you must see you attempt at mastery as something extremely
    necessary and positive.
  - To solve problems will require tremendous amount of effort and
    creativity. Relying on genetics, technology, magic or being nice
    and natural will not save us.
  - We must create our own world or we will die from inaction.
  - You are setting an example of what can be achieved as a master in
    the modern world.


  - People get the mind and quality of brain that they deserve through
    their actions in life.


  - They all possessed that seriousness of the efficient workman which
    first learns to construct the parts properly before it ventures to
    fasion a great whole; they allowed themselves time for it because
    they took more pleasure in making the little, secondary things
    well than in the effect of a dazzling whole.




